# Generated by Django 4.2.2 on 2023-06-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="org_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="organization.master"
            ),
        ),
    ]
