# Generated by Django 4.2.2 on 2023-06-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_branch_org_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="org_id",
            new_name="org",
        ),
    ]
