# Generated by Django 4.2.2 on 2023-06-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_rename_org_id_branch_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reg_Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_name", models.CharField()),
                ("type", models.CharField()),
                ("size", models.CharField()),
                ("country_id", models.CharField()),
                ("is_mandatory", models.BigIntegerField()),
                ("sys_defined", models.BigIntegerField()),
                ("check_duplicate", models.BigIntegerField()),
                ("org_entity_type", models.CharField()),
                ("is_global", models.BigIntegerField()),
                ("comp_settings", models.BigIntegerField()),
                ("data_format", models.CharField()),
                ("allow_special_characters", models.BigIntegerField()),
                ("allow_unregistered", models.BigIntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.master",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="branch",
            old_name="org",
            new_name="org_id",
        ),
        migrations.CreateModel(
            name="RegNo_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateField(auto_now_add=True)),
                ("valid_upto", models.DateField()),
                ("branch_id", models.DateField()),
                ("is_unregistered", models.DateField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.master",
                    ),
                ),
                (
                    "reg_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.reg_types",
                    ),
                ),
            ],
        ),
    ]
