# Generated by Django 4.2.2 on 2023-06-21 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_alter_branch_address_alter_branch_aeo_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Master",
            new_name="Organization",
        ),
    ]
