# Generated by Django 3.2.20 on 2023-08-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('invoice_format', models.PositiveSmallIntegerField(choices=[(1, 'Format 1'), (2, 'Format 2')])),
            ],
        ),
    ]
