# Generated by Django 3.2.19 on 2023-06-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('country_id', models.CharField(max_length=255, null=True)),
                ('company_id', models.CharField(max_length=255, null=True)),
                ('is_global', models.IntegerField(null=True)),
                ('is_active', models.IntegerField(null=True)),
                ('is_consignor', models.IntegerField(null=True)),
                ('is_consignee', models.IntegerField(null=True)),
                ('is_agent', models.IntegerField(null=True)),
                ('is_transporter', models.IntegerField(null=True)),
                ('is_broker', models.IntegerField(null=True)),
                ('is_service_provider', models.IntegerField(null=True)),
                ('is_acc_receivable', models.IntegerField(null=True)),
                ('is_acc_payable', models.IntegerField(null=True)),
                ('is_active_rem', models.IntegerField(null=True)),
                ('is_air_transport', models.IntegerField(null=True)),
                ('trans_airline_id', models.BigIntegerField(null=True)),
                ('is_sea_transport', models.IntegerField(null=True)),
                ('trans_sealine_id', models.BigIntegerField(null=True)),
                ('is_road_transport', models.IntegerField(null=True)),
                ('is_rail_transport', models.IntegerField(null=True)),
                ('location_id', models.BigIntegerField(null=True)),
                ('comp_type', models.CharField(max_length=255, null=True)),
                ('exptr_type', models.CharField(max_length=255, null=True)),
                ('kyc_details_present', models.CharField(max_length=255, null=True)),
                ('doc_status', models.CharField(max_length=255, null=True)),
                ('sales_person_id', models.BigIntegerField(null=True)),
                ('is_affiliate', models.IntegerField(null=True)),
                ('aff_company_id', models.BigIntegerField(null=True)),
                ('denied_party_status', models.CharField(max_length=255, null=True)),
                ('denied_party_checked_on', models.CharField(max_length=255, null=True)),
                ('sales_person_user_id', models.BigIntegerField(null=True)),
                ('global_org_id', models.BigIntegerField(null=True)),
                ('global_org', models.CharField(max_length=255, null=True)),
                ('pay_method', models.CharField(max_length=255, null=True)),
                ('org_edi_code', models.CharField(max_length=255, null=True)),
                ('exptr_status', models.CharField(max_length=255, null=True)),
                ('leid', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
